---
title: "Graph Tweet"
subtitle: "More Examples"
author: "John Little"
date: '`r Sys.Date()`'
output: html_notebook
---

# Preface

Using the graphTweets package with the rtweet package to generate a network graph.  graphTweet can write a file in "gephi format" -- for which Gephi can open and display

http://john-coene.com/packages/graphTweets/examples

```{r, warning=FALSE}
library(graphTweets)
library(tidyverse)
library(rtweet)
library(igraph)
library(networkD3)
library(RColorBrewer)
```

## Get Tweets
```{r getTweets}
dukmbb <- search_tweets("dukembb", n=100, lang = "en")
dukmbb_nRT <- dukmbb%>% 
  filter(is_retweet == FALSE)
```


## Identify Edges
```{r}
edges <- getEdges(data = dukmbb_nRT, tweets = "text", source = "screen_name")

edges <- edges[!duplicated(edges),]

g <- igraph::graph.data.frame(edges, directed = TRUE)

igraph::plot.igraph(g, layout = layout.fruchterman.reingold(g))

```

```{r}
edges <- getEdges(data = dukmbb, tweets = "text", source = "screen_name")
edges <- edges[!duplicated(edges),]

networkD3::simpleNetwork(edges, Source = "source", Target = "target")
```

## Example 2

```{r}

# edges <- getEdges(data = dukmbb, tweets = "text", source = "screen_name")
edges_ex2 <- getEdges(dukmbb_nRT, source = "screen_name", tweets = "text", 
                  str.length = NULL, "favorite_count")
# edges_ex2 <- edges_ex2[!duplicated(edges),]

nodes <- getNodes(edges_ex2, source = "source", target = "target", "favorite_count")

# replace NA with 0
nodes$retweetCount[is.na(nodes$favorite_count)] <- 0

# build graph
g <- igraph::graph.data.frame(edges_ex2, directed = TRUE, vertices = nodes)

```


## make plot for example 2
from http://john-coene.com/packages/graphTweets/examples#example_02

```{r}
pal <- RColorBrewer:::brewer.pal(5, "Dark2")
V(g)$color <- colorRampPalette(pal)(length(V(g)$favorite_count))

# plot vertex size ~ degree
plot(g, layout = layout.fruchterman.reingold(g), vertex.color = V(g)$color,
     vertex.size = log1p(degree(g)) * 3)
```

## Locations
```{r}
dukmbb_location <- users_data(dukmbb)

dukmbb_coords <- lookup_coords(dukmbb_location$location[1], "country:US")

# lookup each location using sapply
dukmbb_coords <-  sapply(dukmbb_location$location, function(x) lookup_coords(x, "country:US")) 

locality <- sapply(dukmbb_location$location, function(x) lookup_coords(x)) 
```

## not working yet
```{r}

unlist(locality[1:5])

# dukmbb_coords[10:15]

foo <- cbind(dukmbb_location$location, data_frame(locality))

foo2 <- cbind(dukmbb_location$location, data_frame(locality[[1]]))

# foo3 <- cbind(dukmbb_location$location, data_frame(locality[[1]][1], data_frame(locality[[1]][2])))



foo[91,]$`dukmbb_location$location`
foo[91,]$"dukmbb_location$location"
foo[91,]$locality[[1]]
foo[91,]$locality[[1]][1]
foo[91,]$locality[[1]][2]
foo[91,]$locality[[1]][3]
foo[91,]$locality[[1]][4]

foo[8,][1]
foo[8,]$locality[[1]]
foo[8,]$locality[[1]][1]
foo[8,]$locality[[1]][2]
foo[8,]$locality[[1]][3]
foo[8,]$locality[[1]][4]

```

