---
title: "testing crosstalk"
author: "John Little"
date: "February 21, 2017"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)     # tidy data, includes readr
library(leaflet)       # GIS/mapping -- An HTML Widget
library(DT)            # DataTables provides filtering, pagination, sorting, and many other features in the tables.  An HTML Widget
library(crosstalk)     # interactive linking between HTML widgets
library(d3scatter)
```


## DataTable
```{r datatable}

sd <- read_csv("https://opendata.socrata.com/api/views/ddym-zvjk/rows.csv")


sd  %>%  
  filter(State == "NC") %>% 
  select(Name, `Facility ID`, Location, lat = Latitude, lng = Longitude) -> sd

datatable(sd)

# datatable(sharebucks, extensions="Scroller", style="bootstrap", class="compact", width="100%", 
#            options=list(deferRender=TRUE,  scrollY=300, scroller=TRUE))
```


## Map
```{r leaflet map}

leaflet(sd) %>% addTiles() %>% addMarkers()

```

## 

```{r crosstalk, eval=FALSE, include=FALSE}

DON'T RUN DOEN'T RUN - DISABLED CHUNK

sharedsd <- SharedData$new(sd)

bscols(
  leaflet(sharedsd) %>% addTiles() %>% addMarkers(),
  datatable(sharedsd)
)
```


  datatable(sharedsd, extensions = "Scroller", style = "bootstrap", class = "compact", width = "100%",
            options = list(deferRender = TRUE, scrollY = 100, scroller = TRUE))


## DT Example from crosstalk mainpage
```{r}

# Wrap data frame in SharedData
sdquake <- SharedData$new(quakes[sample(nrow(quakes), 100),])

# Create a filter input
filter_slider("mag", "Magnitude", sdquake, column=~mag, step=0.1, width=250)

# Use SharedData like a dataframe with Crosstalk-enabled widgets
bscols(
  leaflet(sdquake) %>% addTiles() %>% addMarkers(),
  datatable(sdquake, extensions="Scroller", style="bootstrap", class="compact", width="100%",
    options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
)
```

```{r}
d3scatter(iris, ~Petal.Length, ~Petal.Width, ~Species)
```

```{r}
shared_iris <- SharedData$new(iris)
d3scatter(shared_iris, ~Petal.Length, ~Petal.Width, ~Species)
```

```{r}
shared_iris <- SharedData$new(iris)
bscols(
  d3scatter(shared_iris, ~Petal.Length, ~Petal.Width, ~Species, width="100%", height=300),
  d3scatter(shared_iris, ~Sepal.Length, ~Sepal.Width, ~Species, width="100%", height=300)
)
```

```{r}
shared_quakes <- SharedData$new(quakes[sample(nrow(quakes), 100),])
bscols(
  leaflet(shared_quakes, width = "100%", height = 300) %>%
    addTiles() %>%
    addMarkers(),
  d3scatter(shared_quakes, ~depth, ~mag, width = "100%", height = 300)
)
```

```{r}
shared_mtcars <- SharedData$new(mtcars)
bscols(widths = c(3,NA,NA),
  list(
    filter_checkbox("cyl", "Cylinders", shared_mtcars, ~cyl, inline = TRUE),
    filter_slider("hp", "Horsepower", shared_mtcars, ~hp, width = "100%"),
    filter_select("auto", "Automatic", shared_mtcars, ~ifelse(am == 0, "Yes", "No"))
  ),
  d3scatter(shared_mtcars, ~wt, ~mpg, ~factor(cyl), width="100%", height=250),
  d3scatter(shared_mtcars, ~hp, ~qsec, ~factor(cyl), width="100%", height=250)
)
```

```{r}
# Wrap data frame in SharedData
sd <- SharedData$new(quakes[sample(nrow(quakes), 100),])

# Create a filter input
filter_slider("mag", "Magnitude", sd, column=~mag, step=0.1, width=250)

# Use SharedData like a dataframe with Crosstalk-enabled widgets
bscols(
  leaflet(sd) %>% addTiles() %>% addMarkers(),
  datatable(sd, extensions="Scroller", style="bootstrap", class="compact", width="100%",
    options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
)
```



## TEST HERE
```{r}

sharebucks <- read_csv("https://opendata.socrata.com/api/views/ddym-zvjk/rows.csv")

sharebucks %>% 
  select(Name, `Facility ID`, Location, lat = Latitude, lng = Longitude) -> sharebucks

sharebucks <- SharedData$new(sharebucks)

bscols(
  leaflet(sharebucks) %>% addTiles() %>% addMarkers(),
  datatable(sd, extensions="Scroller", style="bootstrap", class="compact", width="100%",
    options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
  
)



```


```{r datatable_sharebucks, eval=FALSE, include=FALSE}

DON'T RUN  DON'T RUN DON'T RUN DON'T RUN DON'T RUN

  datatable(sharebucks, extensions="Scroller", style="bootstrap", class="compact", width="100%", 
            options=list(deferRender=TRUE,  scrollY=229, scroller=TRUE))
# )
```

