---
title: "testing crosstalk"
author: "John Little"
date: "February 21, 2017"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)     # tidy data, includes readr
library(leaflet)       # GIS/mapping -- An HTML Widget
library(DT)            # DataTables provides filtering, pagination, sorting, and many other features in the tables.  An HTML Widget
library(crosstalk)     # interactive linking between HTML widgets
```



## TEST HERE
```{r}

sharebucks <- read_csv("https://opendata.socrata.com/api/views/ddym-zvjk/rows.csv")

sharebucks %>% 
  filter(State == "NC") %>% 
  select(Name, City, Location, `Facility ID`, lat = Latitude, lng = Longitude) -> sharebucks

sharebucks <- SharedData$new(sharebucks)
```

bscols(
  leaflet(sharebucks) %>% addTiles() %>% addMarkers(),
  datatable(sharebucks, extensions="Scroller", style="bootstrap", class="compact", width="100%",
    options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
)



```{r}
leaflet(sharebucks) %>% addTiles() %>% addMarkers()

datatable(sharebucks, extensions="Scroller", style="bootstrap", class="compact", width="100%",
    options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))

```

