---
title: "Flexdashboards presentation at...."
subtitle: "R we having fun yet‽"
author: "John Little"
date: "`r Sys.Date()`"
output: html_notebook
---

[Data & Visualization Services](http://library.duke.edu/data)

http://is.gd/rfun2017

&nbsp;<br>

## [Rstudio Webinars (VOD)](https://www.rstudio.com/resources/webinars/)

  - [Introducing Flexdashboards](https://www.rstudio.com/resources/webinars/introducing-flexdashboards/); (video and materials)
- [Dashboards made Easy](https://www.rstudio.com/resources/videos/dashboards-made-easy/) - (lightning talk at rstudio::conf 2017)
    
## Rmarkdown - Flexdashboards - the docs

- [Get Started](http://rmarkdown.rstudio.com/flexdashboard/)
        - Also see Gallery and Sample Layouts
- [using](http://rmarkdown.rstudio.com/flexdashboard/using.html) *aka RTFM*
    
## How to

- File > New File > Rmarkdown > From Template > Flex Dashboard
    
## Works With...

- basic text, rmarkdown for HTML and CSS
- comes with: gauges, info-boxes, fa-awesome
- storyboards
- etc...
- Customize menu-bar with **Share/social** & **source-code**
- [HTML Widgets](http://rmarkdown.rstudio.com/developer_html_widgets.html)
    - e.g. leaflet, DT, ggplot2, 
    - interactive with [crosstalk](https://rstudio.github.io/crosstalk/)
- Shiny

## Files
listed in roughly the correct order as presented.  Or see [GitHub](https://github.com/data-and-visualization/Rfun/tree/master/flexdashboards)

- Dashboard - first attempt (columns):  [sbux-after-cols](sbux-after-cols.html)

- Dashboard - columns converted to rows: [sbux-after-rows](sbux-after-rows.Rmd.html)

- Simple to convert html_document to dashboard in the YAML header:  [starbucks-before](sbux-after-cols.html)

- Live Demo done during the presentation:  [awesome-test](awesome-test.html)

- Crosstalk example where leaflet and DT packages work symbiotically.  Note this does not compile on Windows as of this writing.:  [starbucks-flexdashboard-crosstalk](starbucks-flexdashboard-crosstalk.html)

## Video Recording

<iframe src="http://library.capture.duke.edu/Panopto/Pages/Embed.aspx?id=3e301f74-332a-403f-a0f8-b41e19d2822f&v=1" width="720" height="405" style="padding: 0px; border: 1px solid #464646;" frameborder="0"></iframe>

    
    