---
title: "CrossTalk Example"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)     # tidy data, includes readr
library(leaflet)       # GIS/mapping -- An HTML Widget
library(DT)            # DataTables provides filtering, pagination, sorting, and many other features in the tables.  An HTML Widget
library(crosstalk)     # interactive linking between HTML widgets

starbucks <- read_csv("https://opendata.socrata.com/api/views/ddym-zvjk/rows.csv")

starbucks %>% 
  filter(State == "NC") %>% 
  select(Name, City, Location, `Facility ID`, lat = Latitude, lng = Longitude) -> sharebucks

sharebucks <- SharedData$new(sharebucks)
```

Column 
-----------------------------------------------------------------------

### Map

Please note that I ran into **bugs** compiling this example on a **Windows** platform.  It all **worked fine in the docker** instance, a **linux** platform.  As near as I can determine the problem lies with how the leaflet package works on windows.  Thus, on *windows* I rolled back to *leaflet* **version 1.0.1**.  When I did that, leaflet worked fine again but I could not compile a crosstalk example on Windows.

```{r}
# leaflet(sharebucks) %>% addTiles() %>% addMarkers()

leaflet(sharebucks) %>% 
  addTiles() %>% 
  setView(-78.8310, 35.9867, zoom = 10) %>% 
  addMarkers(popup = sharebucks$Name)
```

Column 
-----------------------------------------------------------------------

### DataTable

```{r}
datatable(sharebucks, extensions="Scroller", style="bootstrap", class="compact", width="100%",
    options=list(deferRender=TRUE, scrollY=300, scroller=TRUE))
```
